### ISSUE TITLE
SEARCH unable to get local issuer certificate

### ISSUE THREAD

**Issue by GaspardCulis** [Musare/Musare#227]
Hi, I just launched a self hosted instance, I setup my environment correctly (I guess), but the youtube API does not work for me:
```
|YOUTUBE|           SEARCH unable to get local issuer certificate
|WS|                RUN_ACTION2 APIS_SEARCH_YOUTUBE Searching youtube failed with query "Eclipse". "An error has occured. Please try again later."
```

My key is well defined in the config:
```json
{
	"configVersion": 12,
	"migration": false,
	"secret": "S2Kf4...",
	"port": 8080,
	"url": {
		"host": "my.host.also.configured",
		"secure": true
	},
	"apis": {
		"youtube": {
			"key": "AIza...."
		},
	}
}
```

And here are screeshots of my Google Cloud Project:
![image](https://github.com/user-attachments/assets/0c2c8926-9306-4656-92fd-28595e64a992)
![image](https://github.com/user-attachments/assets/d0d15421-5cbc-48a8-80a4-56aae109e62a)

Am I doing something wrong ?

**Comment by KrisVos130** [comment]
@GaspardCulis Hi, based on "unable to get local issuer certificate" and some quick searches online, this sounds like it's some local issue with your certificates. E.g., if your school/workplace/antivirus/proxy/etc. has installed a custom CA certificate on your PC that is trusted by browsers and such, but not by NodeJS (in Docker?).

A normal use for that, from what I understand, is some firewall or something being able to intercept and analyze requests made to sites that use SSL/TLS, as normally it's encrypted. Or maliciously is possible too.

If you trust it, or if you want to test, you can try doing `npm config set strict-ssl false` in backend (if you use Docker, run it inside the docker container), and restart the backend. Or set `export NODE_TLS_REJECT_UNAUTHORIZED=0` as environment variable (may need to do in Docker container, edit script to set `NODE_TLS_REJECT_UNAUTHORIZED=0` before it starts the backend, or do something different depending on how you're running it and on which OS).

If you're having trouble with that, I can try and help, just let me know how you're running it and on which type of OS/device. Or if you have any other questions.

**Comment by GaspardCulis** [comment]
Hi, thx for blazingly fast response, my musare backend is indeed running behind a [Caddy](https://caddyserver.com/) proxy, here is my config:
```Caddyfile
music.myhost.com {
    root * ${musare-frontend}
    file_server

    @websockets {
        path /backend/*
        header Connection upgrade
        header Upgrade websocket
    }

    reverse_proxy @websockets localhost:32483

    handle_path /backend/*  {
        reverse_proxy localhost:32483
    }
}
```
Adding the `NODE_TLS_REJECT_UNAUTHORIZED=0` env var changed the error to:
```sh
|YOUTUBE|           SEARCH Request failed with status code 403
|WS|                RUN_ACTION2 APIS_SEARCH_YOUTUBE Searching youtube failed with query "eclipse". "An error has occured. Please try again later.
```

Take a look at my [dotfiles](https://github.com/GaspardCulis/dotfiles/blob/c73204ce61c39471ecd18aeaccb6682ecb8b941e/services/musare/default.nix) if you want the whole picture

**Comment by KrisVos130** [comment]
Hi, thanks for that, and good to see the CA issue is at least solved. The dotfiles helps a lot as well.

I tested a few things, and may have found the reason. If I mistype my YouTube API key, it returns with error code 400. But if I just have an empty string in my `local.json` for the API key, I get error code 403.

Based on that, I guess it's because you set the `YOUTUBE_API_KEY` environment variable, but that probably doesn't do anything. `backend/config/custom-environment-variables.json` lists some environment variables that can be used, and that doesn't list `YOUTUBE_API_KEY`. You did list it in your original comment, but not sure if you still have that, and if it's in the proper location (`backend/config/local/json`) or not, or if the environment variable somehow messes something up?

So I would check that, https://github.com/Musare/Musare/blob/master/.wiki/Configuration.md is up-to-date I think. But if you need any help, let me know.

**Comment by GaspardCulis** [comment]
Actually I do not set the `YOUTUBE_API_KEY` environment variable, it is provided in the `config.json` as you can see [here](https://github.com/GaspardCulis/dotfiles/blob/c73204ce61c39471ecd18aeaccb6682ecb8b941e/services/musare/default.nix#L89).
This is nix syntax but it renders the `config.json` file gets rendered to `/run/secrets-rendered/...`:
![image](https://github.com/user-attachments/assets/e81298b4-1685-4f45-a787-456453cec2ac)
And then I the docker container mounts it [here](https://github.com/GaspardCulis/dotfiles/blob/c73204ce61c39471ecd18aeaccb6682ecb8b941e/services/musare/default.nix#L121).
Also I noticed some indentation issues in my config for the `config.json` file which I fixed [here](https://github.com/GaspardCulis/dotfiles/commit/2cb3a9851de0cdc0cc5cdc1f1c91421aa8ed92c6), and this supposed fix kinda broke the config and now the backend uses the default db addresses, which were overwritten in my config:
![image](https://github.com/user-attachments/assets/905a17a7-ec62-442d-8361-0a15ddfe269f)
How do you load the `config.json`, could different indentation break it ?

**Comment by KrisVos130** [comment]
Ah, that makes more sense, my bad.

Not sure if I'm reading the file correctly, but is it trying to mount that config file as being in the root directory of the project, or the root directory of the backend, named `config.json`? Because it's supposed to be in the `backend/config` folder, and be named `local.json`. If it's not doing that, then that's probably the issue, and that explains why the config isn't working.

Indentation shouldn't break anything. If the config file isn't named local.json and isn't in the config directory, it would also explain that it's still trying to use redis/mongo for the Redis/MongoDB hostname/url.

**Comment by GaspardCulis** [comment]
In the docker container, the backend app is located in `/opt/app` (so the docker entry point is `node /opt/app/index.js`), and I mount the config to `/opt/app/config/config.json`. So you say that it must be mouted at `/opt/app/config/local.json` ?
EDIT: Actually it was mounted at `/opt/app/config.json`, updated my config in [this commit](https://github.com/GaspardCulis/dotfiles/commit/ed4e4b1f2c93b1e3456bb556c1e24b543067cc3c) and now it works. My bad thx for your response. Maybe just add a few checks to the config when initializing the app

**Comment by KrisVos130** [comment]
Good to hear, and I'll make a note to see if we can improve documentation or add some checks to make it clearer.

Thanks for the feedback and trying out Musare. I'll close this for now, but feel free to reach out if you have any other questions/problems/suggestions.
